# services/analytics-python/question_generator.py
#
# Generates quiz questions so nobody ever has to hand-type them into the DB.
#
# Two modes, chosen automatically:
#   1. LLM mode  — if LLM_PROVIDER + the matching API key are set, real
#      questions are generated by calling that provider's chat/completions
#      endpoint. Works with ANY OpenAI-compatible or Anthropic-compatible
#      model — just point it at a different provider/model name via env vars.
#   2. Template mode (default, zero-config) — if no key is configured, a
#      local procedural generator builds valid, varied questions from a
#      small fact bank + randomized phrasing so the app is playable with
#      NO external dependency and NO manual data entry.
#
# Either way, callers get back a validated list of:
#   {questionText, options: [4 strings], correctOptionIndex, difficulty}

import json
import os
import random
from typing import List, Dict

import requests

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "").lower()  # "openai" | "anthropic" | ""
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-3-5-haiku-20241022")

VALID_CATEGORIES = [
    "programming", "science", "mathematics", "history", "geography", "entertainment",
]


def llm_configured() -> bool:
    if LLM_PROVIDER == "openai":
        return bool(OPENAI_API_KEY)
    if LLM_PROVIDER == "anthropic":
        return bool(ANTHROPIC_API_KEY)
    return False


def _build_prompt(category: str, count: int) -> str:
    return (
        f"Generate {count} multiple-choice trivia questions for the category '{category}'. "
        "Respond with ONLY a JSON array (no prose, no markdown fences). Each element must be "
        'an object exactly like: {"questionText": "...", "options": ["...", "...", "...", "..."], '
        '"correctOptionIndex": 0, "difficulty": "easy|medium|hard"}. '
        "Options must have exactly 4 entries, correctOptionIndex must be the 0-based index of the "
        "correct option, and questions must be factually accurate and unambiguous."
    )


def _call_openai(prompt: str) -> str:
    resp = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},
        json={
            "model": OPENAI_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.7,
        },
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"]


def _call_anthropic(prompt: str) -> str:
    resp = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        },
        json={
            "model": ANTHROPIC_MODEL,
            "max_tokens": 1500,
            "messages": [{"role": "user", "content": prompt}],
        },
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    return "".join(block.get("text", "") for block in data.get("content", []))


def _parse_llm_json(raw_text: str) -> List[Dict]:
    # Models sometimes wrap JSON in markdown fences despite instructions — strip defensively.
    cleaned = raw_text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        cleaned = cleaned.replace("json\n", "", 1).replace("json\r\n", "", 1)
    return json.loads(cleaned)


def _validate_question(q: Dict) -> bool:
    if not isinstance(q.get("questionText"), str) or not q["questionText"].strip():
        return False
    options = q.get("options")
    if not isinstance(options, list) or len(options) != 4:
        return False
    if not all(isinstance(o, str) and o.strip() for o in options):
        return False
    idx = q.get("correctOptionIndex")
    if not isinstance(idx, int) or idx < 0 or idx > 3:
        return False
    return True


VALID_DIFFICULTIES = ("easy", "medium", "hard")


def generate_via_llm(category: str, count: int) -> List[Dict]:
    prompt = _build_prompt(category, count)

    if LLM_PROVIDER == "openai":
        raw = _call_openai(prompt)
    elif LLM_PROVIDER == "anthropic":
        raw = _call_anthropic(prompt)
    else:
        raise RuntimeError(f"Unsupported LLM_PROVIDER: '{LLM_PROVIDER}'")

    parsed = _parse_llm_json(raw)
    valid = [q for q in parsed if _validate_question(q)]

    for q in valid:
        # Options/correctOptionIndex are already schema-checked by
        # _validate_question above. difficulty is NOT — clamp it here,
        # since this service writes directly via PyMongo and bypasses the
        # Node backend's Mongoose `enum` validator entirely.
        if q.get("difficulty") not in VALID_DIFFICULTIES:
            q["difficulty"] = "medium"
        q["category"] = category

    return valid


# ---------------------------------------------------------------------------
# Template mode — zero-config fallback so QuizNest is playable immediately,
# with no API key and no manually-authored question file.
# ---------------------------------------------------------------------------
_FACT_BANK = {
    "programming": [
        ("a variable that cannot be reassigned after initialization", "constant"),
        ("a function that calls itself", "recursive function"),
        ("a bug caused by accessing memory outside allocated bounds", "buffer overflow"),
        ("a data structure that follows First In, First Out order", "queue"),
        ("a data structure that follows Last In, First Out order", "stack"),
        ("code that documents itself through clear naming", "self-documenting code"),
        ("a loop that never terminates", "infinite loop"),
        ("a design pattern that ensures only one instance of a class exists", "singleton"),
    ],
    "science": [
        ("the powerhouse of the cell", "mitochondria"),
        ("the force that pulls objects toward Earth", "gravity"),
        ("the process plants use to convert sunlight into energy", "photosynthesis"),
        ("the smallest unit of an element that retains its properties", "atom"),
        ("the study of celestial objects and phenomena", "astronomy"),
        ("the gas humans need to breathe to survive", "oxygen"),
        ("the theory describing how species change over generations", "evolution"),
        ("the basic unit of heredity", "gene"),
    ],
    "mathematics": [
        ("a number that can only be divided evenly by 1 and itself", "prime number"),
        ("the ratio of a circle's circumference to its diameter", "pi"),
        ("a triangle with all three sides equal", "equilateral triangle"),
        ("the result of multiplying a number by itself", "square"),
        ("a fraction where the numerator is larger than the denominator", "improper fraction"),
        ("the study of shapes and their properties", "geometry"),
        ("the branch of math dealing with rates of change", "calculus"),
        ("a number with no fractional or decimal part", "integer"),
    ],
    "history": [
        ("the war fought between the North and South United States", "the Civil War"),
        ("the ancient wonder located in Giza, Egypt", "the Great Pyramid"),
        ("the event that ended World War Two in Europe", "V-E Day"),
        ("the ship that famously sank in 1912", "the Titanic"),
        ("the wall that divided Berlin during the Cold War", "the Berlin Wall"),
        ("the revolution that began in France in 1789", "the French Revolution"),
        ("the empire ruled by Julius Caesar", "the Roman Empire"),
        ("the document that declared American independence in 1776", "the Declaration of Independence"),
    ],
    "geography": [
        ("the longest river in the world", "the Nile"),
        ("the largest desert in the world", "the Sahara"),
        ("the smallest country in the world by area", "Vatican City"),
        ("the tallest mountain in the world", "Mount Everest"),
        ("the largest ocean on Earth", "the Pacific Ocean"),
        ("the continent home to the most countries", "Africa"),
        ("the largest country in the world by area", "Russia"),
        ("the strait separating Europe and Africa", "the Strait of Gibraltar"),
    ],
    "entertainment": [
        ("the studio behind Toy Story and Finding Nemo", "Pixar"),
        ("the fictional wizarding school in Harry Potter", "Hogwarts"),
        ("the streaming platform known for 'red envelope' origins", "Netflix"),
        ("the instrument with 88 keys", "the piano"),
        ("the award given for excellence in film", "the Oscar"),
        ("the genre defined by spaceships and aliens", "science fiction"),
        ("the console maker behind the Switch", "Nintendo"),
        ("the art form combining music, acting, and dance on stage", "musical theater"),
    ],
}

_TEMPLATES = [
    "What is {clue}?",
    "Which term best describes {clue}?",
    "In {category}, what do we call {clue}?",
]


def generate_via_template(category: str, count: int) -> List[Dict]:
    bank = _FACT_BANK.get(category, _FACT_BANK["entertainment"])
    pool = bank * ((count // len(bank)) + 1)  # repeat if more questions requested than facts
    random.shuffle(pool)
    selected = pool[:count]

    questions = []
    for clue, answer in selected:
        template = random.choice(_TEMPLATES)
        question_text = template.format(clue=clue, category=category.capitalize())

        # De-duplicate by answer text first — if the fact bank ever contains
        # two different clues sharing an answer, we must not offer the same
        # option twice within a single question.
        distractor_pool = list(dict.fromkeys(a for (_, a) in bank if a != answer))
        random.shuffle(distractor_pool)
        wrong_options = distractor_pool[:3]
        while len(wrong_options) < 3:  # pad if the category bank is very small
            wrong_options.append(f"none of the above ({random.randint(1,99)})")

        options = wrong_options + [answer]
        random.shuffle(options)
        correct_index = options.index(answer)

        display_options = [o.capitalize() for o in options]
        # Final safety net: capitalize() could theoretically collapse two
        # distinct strings to the same display text. Never ship duplicate
        # options to the client — disambiguate rather than risk an
        # unwinnable or misleading question.
        seen = {}
        for i, opt in enumerate(display_options):
            if opt in seen:
                display_options[i] = f"{opt} (option {i + 1})"
            else:
                seen[opt] = i

        questions.append(
            {
                "category": category,
                "questionText": question_text[0].upper() + question_text[1:],
                "options": display_options,
                "correctOptionIndex": correct_index,
                "difficulty": random.choice(["easy", "medium", "hard"]),
            }
        )

    return questions


def generate_questions(category: str, count: int = 10) -> List[Dict]:
    if category not in VALID_CATEGORIES:
        raise ValueError(f"Unknown category '{category}'. Must be one of {VALID_CATEGORIES}.")

    if llm_configured():
        try:
            questions = generate_via_llm(category, count)
            if questions:
                return questions
        except Exception:
            # Fall through to template mode rather than leaving the category empty —
            # the game staying playable matters more than a single failed API call.
            pass

    return generate_via_template(category, count)
